Update dotnet-desktop.yml
broo

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -74,6 +74,11 @@ jobs:
       with:
         dotnet-version: 8.0.x
 
+    - name: Check PFX file exists
+      run: |
+        ls -l
+        ls -l GitHubActionsWorkflow.pfx || echo "File not found"
+    
     # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
     - name: Setup MSBuild.exe
       uses: microsoft/setup-msbuild@v2
@@ -96,6 +101,13 @@ jobs:
         $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
         [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
 
+    - name: Decode PFX
+      run: |
+        echo "${{ secrets.PFX_BASE64 }}" | base64 -d > GitHubActionsWorkflow.pfx
+        file GitHubActionsWorkflow.pfx
+        openssl pkcs12 -info -in GitHubActionsWorkflow.pfx -nokeys -passin pass:${{ secrets.PFX_PASSWORD }} || echo "Failed to open PFX"
+      shell: bash
+    
     # Create the app package by building and packaging the Windows Application Packaging project
     - name: Build the Windows Application Packaging Project (wapproj)
       run: msbuild $env:Solution_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
